//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mukhtarenkov_DemExam_variant_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoServiceDBEntities : DbContext
    {
        public AutoServiceDBEntities()
            : base("name=AutoServiceDBEntities")
        {
        }

        private static AutoServiceDBEntities _context;
        public static AutoServiceDBEntities GetContext()
        {
            if (_context == null)
                _context = new AutoServiceDBEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderuserlist> orderuserlist { get; set; }
        public virtual DbSet<shift> shift { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<userlist> userlist { get; set; }
        public virtual DbSet<userrole> userrole { get; set; }
    }
}
