//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mukhtarenkov_DemExam_variant_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderuserlist
    {
        public int OrderUserListId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual order order { get; set; }
        public virtual user user { get; set; }
    }
}
