//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mukhtarenkov_DemExam_variant_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.orderuserlist = new HashSet<orderuserlist>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string CarElement { get; set; }
        public string Details { get; set; }
        public Nullable<int> AmountDamage { get; set; }
        public string Liquids { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderuserlist> orderuserlist { get; set; }
    }
}
